models/Purchase.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;
use dektrium\user\models\User;
use app\components\behaviors\UserBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "purchase".
 *
 * @property integer $id
 * @property string $date
 * @property integer $store_id
 * @property integer $user_id
 *
 * @property User $user
 * @property Store $store
 * @property Products[] $products
 */
class Purchase extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'store_id'], 'required'],
            //['date', 'date', 'format' => 'php:U'],            
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'userBehavior' => UserBehavior::className(),
            'timestampBehavior' => TimestampBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date' => Yii::t('app', 'Date'),
            'store_id' => Yii::t('app', 'Store ID'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(Store::className(), ['id' => 'store_id']);
    }
	
    public function getPurchasedProducts()
    {
        return $this->hasMany(PurchaseHasProduct::className(), ['purchase_id' => 'id']);
    }
    
    public function getProducts()
    {
        return $this->hasMany(Product::classname(), ['id' => 'product_id'])
                ->via('purchasedProducts'); 
    }

    public function getProductsDataProvider()
    {
        return new ActiveDataProvider([
                'query' => PurchaseHasProduct::find()->where(['purchase_id' => $this->id]),
        ]);
    }
    
    public function getFormAttribs()
    {
        return [
            [
                'attribute' => 'product_id',
                'value' => $this->products->brand,
                'type' => \kartik\builder\TabularForm::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\Typeahead::className(),
                'options' => [
                    'dataset' => ['abc','def','ghi']
                ]
            ],
            
            
            'qty' => [
                'type' => \kartik\builder\TabularForm::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\TouchSpin::className(),
            ],
            'cost' => [
                'type' => \kartik\builder\TabularForm::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\InputWidget::className(),
            ]
            
        ];
    }
}
/*
                    'qty',
                    'product.brand',
                    'product.type',
                    'product.desc',
                    'cost:decimal:Price',
                    'discount',
 * 
 */

controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Product;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;
use yii\helpers\Json;
use yii\db\Connection;
use yii\db\Command;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();
        if (Yii::$app->request->isAjax) {
            return $this->createProduct(Yii::$app->request->post());
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionUsers()
    {
        $results = [];
        
        if (($models = Product::find()->users()->all()) !== null) {
            foreach ($models as $model)
            {
                $results[] = ['value' => 
                    $model->brand . ', ' . $model->type . ', ' . $model->desc
                ];
            }
        }
        return json_encode($results);
    }
    
    public function actionFind($q)
    {
        $results = [];
        $db = Yii::$app->db;
        $products = $db->createCommand("SELECT * FROM (" .
                "SELECT id,brand,type,[[desc]],amount,unit,user_id," .
                    "CONCAT_WS(' ',brand,type,[[desc]],amount)" .
                    " AS prod" . 
                " FROM product) t " .
                "WHERE t.prod LIKE :query AND t.user_id=:user")
            ->bindValue(':query', "%$q%")
            ->bindValue(':user', Yii::$app->user->id)
            ->queryAll();
        
        foreach ($products as $product) {
            $results[] = [
                'id' => $product['id'],
                'brand' => $product['brand'],
                'type' => $product['type'],
                'desc' => $product['desc'],
                'amount' => $product['amount'],
                'unit' => $product['unit'],
                'value' =>  $product['brand'] . ', ' .
                            $product['type'] . ', ' .
                            $product['desc'] . 
                            (($product['amount'] !== null) ?
                                ' (' . $product['amount'] . ' ' .
                                $product['unit'] . ')' :
                                '')
                            
            ];
        }
        echo Json::encode($results);
    }
    
    public function actionByBrand($type = null, $desc = null)
    {
        $results = [];
        $products = Product::find()->users()
                ->where($type ? 'type LIKE "%' . $type .'%"' : '')
                ->andWhere($desc ? 'desc LIKE "%' . $desc .'%"' : '')
                ->all();
        foreach ($products as $product) 
        {
            $results[] = ['value' => $product->brand];
        }
        return json_encode($results);
    }
    public function actionByType($brand = null, $desc = null)
    {
        $results = [];
        $products = Product::find()->users()
                ->where($brand ? 'brand LIKE "%' . $brand .'%"' : '')
                ->andWhere($desc ? 'desc LIKE "%' . $desc .'%"' : '')
                ->all();
        foreach ($products as $product) 
        {
            $results[] = ['value' => $product->type];
        }
        return json_encode($results);
    }
    public function actionByDesc($type = null, $brand = null)
    {
        $results = [];
        $products = Product::find()->users()
                ->where($type ? 'type LIKE "%' . $type .'%"' : '')
                ->andWhere($brand ? 'desc LIKE "%' . $brand .'%"' : '')
                ->all();
        foreach ($products as $product) 
        {
            $results[] = ['value' => $product->desc];
        }
        return json_encode($results);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    private function createProduct($data)
    {
        $product = new Product();
        $attrs = explode(',', $data['name']);
        $product->setAttributes([
            'brand' => $attrs[0],
            'type' => $attrs[1],
            'desc' => $attrs[2],
            'amount' => $attrs[3],
            'unit' => $attrs[4],
        ]);
        
        if ($product->save())
            return $product->id;
        else
            return 0;
    }
}

controllers/PurchaseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Purchase;
use app\models\PurchaseHasProduct;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PurchaseController implements the CRUD actions for Purchase model.
 */
class PurchaseController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Purchase models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Purchase::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Purchase model.
     * 
     * 
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'hasProductModel' => new \app\models\PurchaseHasProduct,
            'productModel' => new \app\models\Product,
        ]);
    }

    /**
     * Creates a new Purchase model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Purchase();
        $hasProduct = new \app\models\PurchaseHasProduct();
        $product = new \app\models\Product();

        if (Yii::$app->request->isAjax) {
            if ($this->createPurchase(Yii::$app->request->post())) {
                Yii::$app->getSession()->setFlash('success', 'Purchase created');
                return true; //$this->redirect(['create']);
            } else {
                return false;
            }
            
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'hasProduct' => $hasProduct,
                'product' => $product,
            ]);
        }

    }

    /**
     * Updates an existing Purchase model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Purchase model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
		
        return $this->redirect(['index']);
    }

    /**
     * Finds the Purchase model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Purchase the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Purchase::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    private function createPurchase($data)
    {
        $purchase = new Purchase();
        $purchase->setAttributes([
            'store_id' => intval($data['purchase']['store']),
            'date' => intval($data['purchase']['date'])
        ]);
        $purchase->save();

        foreach ($data['products'] as $product)
        {
            $hasProduct = new PurchaseHasProduct();
            $hasProduct->setAttributes([
                'purchase_id' => $purchase->id,
                'product_id' => intval($product['productId']),
                'qty' => intval($product['qty']),
                'cost' => $product['cost'],
                'discount' => $product['discount']
            ], false);
            $result = $hasProduct->save();
            if (!$result) break;
        }

        return true;
    }
}

views/purchase/old/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\widgets\ActiveForm;
use kartik\datecontrol\DateControl;
use app\models\Store;

/* @var $this yii\web\View */
/* @var $model app\models\Purchase */
/* @var $hasProduct app\models\PurchaseHasProduct */
/* @var $product app\models\Product */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="purchase-form">

    <?php 
        $form = ActiveForm::begin(); 
        $model->date = date('Y-m-d'); 
    ?>
  
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'date')->widget(DateControl::className(),[
                    'type' => DateControl::FORMAT_DATE,
                    'displayFormat' => 'php:d/m/Y',
                    'saveFormat' => 'php:Y-m-d',
                    'readonly' => true,
                    'options' => [
                        'pluginOptions' => [
                            'autoclose' => false,
                            'todayHighlight' => true,
                        ],
                    ],
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'store_id')->dropDownList(
                    ArrayHelper::map(Store::find()->all(), 'id', 'name')
            ) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php $form::end(); ?>
    
</div>

views/purchase/old/_grid.php
<div class="product-grid">
    
    <div class="products-grid">
        <table class="table table-striped table-bordered" id="products-table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                    <th>Discount</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    
    <script id="productRow" type="text/template">
        <td><%= brand %></td>
        <td><%= qty %></td>
        <td><%= cost %></td>
        <td><%= discount %></td>
        <td>
            <a href="#" class="edit" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="#" class="delete" title="Delete"><span class="glyphicon glyphicon-trash"></span></a>
        </td>
    </script>
    
</div>

views/purchase/old/_productForm.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\web\View;
use kartik\widgets\Typeahead;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $hasProduct app\models\PurchaseHasProduct */
/* @var $product app\models\Product */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-form">
    <?php $productForm = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group field-product-id required">
                <label class="control-label" for="product-id">Product</label>
                <input type="hidden" id="product-id" class="form-control required">
                <?php $suggestionTemplate = '<p>{{brand}}, {{type}}, {{desc}}</p>' .
                               '<p><sm>{{amount}} {{unit}}</sm></p>'; 
                       $footerTemplate = '<p class="text-center"><a href="#">Save this item</a></p>';
                ?>
                    
                <?= Typeahead::widget([
                        'name' => 'product-finder',
                        'pluginOptions' => ['highlight'=>true],
                        'pluginEvents' => [
                            'typeahead:selected' => "function(obj, datum, name) { $('#product-id').val(datum.id); }",
                            
                        ],
                        'dataset' => [
                            [
                                'remote' => Url::to(['product/find']) . '?q=%QUERY',
                                'limit' => 10,
                                'templates' => [
                                    'suggestion' => new JsExpression("Handlebars.compile('${suggestionTemplate}')"),
                                    //'footer' => new JsExpression("Handlebars.compile('${footerTemplate}')"),
                                    'empty' => new JsExpression("Handlebars.compile('${footerTemplate}')")
                                ]
                            ]
                        ]
                ]) ?>
                <div class="help-block"></div>
            </div>
            
        </div>
        <div class="col-sm-6">
            <?= $productForm->field($hasProduct, 'cost')->input('number',['value' => 0, 'onclick' => 'this.select();']) ?>
        </div>
        
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $productForm->field($hasProduct, 'qty')->input('number',['value' => 1, 'onclick' => 'this.select();']) ?>
        </div>
        <div class="col-sm-6">
            <?= $productForm->field($hasProduct, 'discount')->input('number',['value' => 0, 'onclick' => 'this.select();']) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($hasProduct->isNewRecord ? Yii::t('app', 'Add') : Yii::t('app', 'Update'), ['class' => $hasProduct->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php $productForm->end(); ?>
    
</div>

<?php $this->registerJs("$('[name=\"product-finder\"]').on('blur', function() {" .
        "if ($('[name=\"product-finder\"]').val() === '') {" .
            "$('#product-id').val('');" .
        "}" .
        "if ($('#product-id').val() === '') {" .
            "$('.field-product-id .help-block').text('Product cannot be blank.');" .
            "$('.field-product-id').addClass('has-error');" .
            "$('[name=\"product-finder\"]').addClass('has-error');" .
            "$('.field-product-id').removeClass('has-success');" .
        "} else {" .
            "$('.field-product-id .help-block').text('');" .
            "$('.field-product-id').removeClass('has-error');" .
            "$('[name=\"product-finder\"]').removeClass('has-error');" .
            "$('.field-product-id').addClass('has-success');" .
        "}" .
    "});" .
        "$(document).on('focus', 'input', function() { this.select(); });", 
    View::POS_READY);
?>

views/purchase/old/create.php
<?php

use yii\helpers\Html;
use app\assets\PurchaseAppAsset;

/* @var $this yii\web\View */
/* @var $model app\models\Purchase */
/* @var $hasProduct app\models\PurchaseHasProduct */
/* @var $product app\models\Product */

PurchaseAppAsset::register($this);

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Purchase',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Purchases'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="purchase-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'hasProduct' => $hasProduct,
        'product' => $product,
    ]) ?>
    
    <?= $this->render('_productForm', [
        'hasProduct' => $hasProduct,
        'product' => $product,
    ]) ?>
    
    <?= $this->render('_grid', [
        
    ]) ?>

    
</div>

views/purchase/old/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Purchases');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="purchase-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Purchase',
]), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => 'Date',
                'format' => 'date',
                'value' => function($data) { return $data->date; }
            ],
            
            'store.name',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/purchase/old/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Purchase */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Purchase',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Purchases'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="purchase-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/purchase/old/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use dektrium\user\models\User;
use app\components\widgets\cYii\CYii;

/* @var $this yii\web\View */
/* @var $model app\models\Purchase */
/* @var $hasProductModel app\models\PurchaseHasProduct */
/* @var $productModel app\models\Product */

$this->title = $model->store->name . ' - ' . $model->date;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Purchases'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="purchase-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= yii\grid\GridView::widget([
            'dataProvider' => $model->productsDataProvider,
            'columns' => [
                    'qty',
                    'product.brand',
                    'product.type',
                    'product.desc',
                    'cost:decimal:Price',
                    'discount',
            ],
    ]) ?>

</div>